### ISSUE TITLE
Unaligned crop error unhelpful

### ISSUE THREAD

**Issue by matteosaporiti** [tp7/vinverse#1]
When using vinverse with unaligned crops the resulting error (in AvsPmod) is

> Traceback (most recent call last):
>   File "avsp.pyo", line 9940, in OnPaintVideoWindow
>   File "avsp.pyo", line 13040, in PaintAVIFrame
>   File "pyavs.pyo", line 717, in DrawFrame
>   File "pyavs.pyo", line 707, in _GetFrame
>   File "pyavs.pyo", line 273, in _GetFrame
>   File "avisynth.pyo", line 499, in GetPitch
> ValueError: NULL pointer access
> instead of the 'nice' "Invalid memory alignment. For God's sake, stop using unaligned crop!" which would be helpful in correcting the script's crops.

The test was made with a simple sourcefilter, resize, crop, vinverse, the pc I'm testing with is a Core i7 3770k, the version of avisynth I'm running is 2.6a5.

**Comment by tp7** [comment]
Can't reproduce it. It's possible that this issue isn't related to crop at all.
Please post your script.

**Comment by matteosaporiti** [comment]
I've updated AvsPmod to 2.5.1 (I had the 2.4.0 around) and now I can see the correct error.
I thought that the error would have been displayed like a black clip with red text (like it happens for Vinverse(uv=4)) instead of a message window, so I didn't think of checking if everything was updated to their latest version.
Probably an old bug of AvPmod.
Sorry for the wrong report.
